### ISSUE TITLE
Wrong translation "Nouveau concertation"

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim#250]
**Describe the bug**
In admin panel, button to create new participatory process "nouveau concertation"

**To Reproduce**
1. Go to https://demo.decidim.opensourcepolitics.eu/admin/participatory_processes

**Expected behavior**
Instead of "nouveau concertation" should be "nouvelle concertation"

**Screenshots**
<img width="989" alt="capture d ecran 2018-09-11 a 11 23 46" src="https://user-images.githubusercontent.com/11473995/45351074-977c1680-b5b5-11e8-89e8-f02f4219854e.png">

**Extra data (please complete the following information):**
 - Decidim installation: demo, mel, nancy

**Comment by juliesimon** [comment]
The problem is, now, this button is build with "Nouveau" + "concertation" (parfois "projet"), "assemblée", "bulletin d'information", "utilisateur".

See code:
```
    admin:
      actions:
        add: Ajouter
        browse: Parcourir
        export: Exporter
        manage: Gérer
        new: Nouveau %{name}
        permissions: Autorisations
        reject: Rejeter
        verify: Vérifier
```

So we need to create new translation key for each "Nouveau" button if we want it to be perfect.

For a quick fix, we can go back to before where it was just "Nouveau" on the button. It's not perfect but it's still better than "Nouveau concertation"
