### ISSUE TITLE
Translation "email_intro" is not working in email

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#50]
On pompano.osp.cat, when there is a new comment, the mail that is sent to the administrator is not using the french translation for the `email_intro` variable  :  
<img width="805" alt="capture d ecran 2018-03-12 a 14 02 25" src="https://user-images.githubusercontent.com/29771726/37285096-317a60fe-25fe-11e8-91c0-56870fa47e3b.png">

But we can see in the locale file `decidim/decidim_comments/config/locales/fr.yml` that `email_intro` is translated in french

```
    events:
      comments:
        comment_created:
          comment:
            email_intro: '"%{resource_title}" a été commenté. Vous pouvez lire le commentaire sur cette page:'
            email_outro: Vous avez reçu cette notification parce que vous suivez "%{resource_title}" ou son auteur. Vous pouvez annuler ces notifications à partir du lien précédent.
            email_subject: Un nouveau commentaire a été publié par %{author_name} dans %{resource_title}
            notification_title: Un nouveau commentaire a été publié par <a href="%{author_path}">%{author_name} %{author_nickname}</a> dans <a href="%{resource_path}">%{resource_title}</a>
```
